apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-ring-buffer-ens192
spec:
  config:
    ignition:
      version: 3.1.0
    systemd:
      units:
      - contents: |
          [Unit]
          Description=Set tx and rx ring buffer for interface %i
          After=network-online.target
          Wants=network-online.target
          [Service]
          Type=oneshot
          TimeoutStartSec=0
          RemainAfterExit=true
          ExecStartPre=/bin/podman pull quay.io/danhawker/macgyver:latest
          ExecStartPre=/bin/podman start macgyver
          ExecStartPre=/bin/podman exec -- bash -c "export ENS=`/usr/sbin/ip addr | grep ens | grep UP | awk -F : '{print $2}'`; for i in $ENS;do /usr/sbin/ethtool -G $i rx 4096 tx 4096;done"
          #ExecStartPre=/bin/podman exec macgyver /usr/sbin/ethtool -G ens192 rx 4096 tx 4096
          ExecStart=/bin/podman exec macgyver /usr/sbin/ethtool -g ens192
          ExecStartPost=/bin/podman stop macgyver
          ExecStop=/bin/podman rm macgyver
          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: mco-ethtool-ring-buffer@ens192.service